from flask import Flask, request, jsonify
import torch
from transformers import AutoModel
import numpy as np
from scipy.signal import resample
from biosppy.signals.tools import filter_signal
from flask_cors import CORS
app = Flask(__name__)
CORS(app, resources={r"/predict": {"origins": "*"}}, methods=['POST'], allow_headers=['Content-Type'])
def apply_filter(signal, filter_bandwidth, fs=500):
    order = int(0.3 * fs)
    signal, _, _ = filter_signal(signal=signal, ftype='FIR', band='bandpass',
                                order=order, frequency=filter_bandwidth,
                                sampling_rate=fs)
    return signal
def scaling(seq, smooth=1e-8):
    return 2 * (seq - np.min(seq, axis=1)[None].T) / (np.max(seq, axis=1) - np.min(seq, axis=1) + smooth)[None].T - 1
def ecg_preprocessing(ecg_signal, original_frequency, target_frequency=100, band_pass=[0.05, 47]):
    ecg_signal = np.atleast_2d(ecg_signal)[:1]
    ecg_signal = resample(ecg_signal, int(ecg_signal.shape[-1] * (500 / original_frequency)), axis=1)
    ecg_signal = apply_filter(ecg_signal, band_pass)
    ecg_signal = scaling(ecg_signal)
    if target_frequency and target_frequency != 500:
        ecg_signal = resample(ecg_signal, int(ecg_signal.shape[-1] * (target_frequency / 500)), axis=1)
    return ecg_signal
model = AutoModel.from_pretrained("Edoardo-BS/hubert-ecg-base", trust_remote_code=True)
model.eval()
def get_ecg_parameters(heart_rate):
    rr_interval = 60 / heart_rate * 1000 if heart_rate > 0 else 0
    return {
        "heart_rate_bpm": f"{heart_rate}",
        "rr_interval_ms": f"{rr_interval:.0f}",
    }
def interpret_feature_vector(feature_vector, heart_rate):
    mean_val = np.mean(feature_vector)
    std_val = np.std(feature_vector)
    if -0.1 < mean_val < 0.1 and std_val < 0.81:
        diagnosis = "Normal Sinus Rhythm"
        recommendation = "The ECG appears to be within normal limits. Continue routine monitoring."
    elif std_val > 1.0:
        diagnosis = "Possible Arrhythmia Detected"
        recommendation = "Irregularities detected in the ECG pattern. A consultation with a cardiologist is recommended."
    else:
        diagnosis = "Uncertain Findings"
        recommendation = "The ECG pattern is inconclusive. Further analysis or a longer monitoring period may be needed."
    return {
        "analysis_method": "heuristic",
        "disclaimer": (
            "Generated by a threshold heuristic over HuBERT-ECG embeddings, not by a "
            "trained diagnostic classifier. For demonstration only — not a medical "
            "diagnosis."
        ),
        "diagnosis": diagnosis,
        "recommendation": recommendation,
        "ecg_parameters": get_ecg_parameters(heart_rate),
        "feature_vector_summary": {
            "mean": float(mean_val),
            "std_dev": float(std_val),
            "min": float(np.min(feature_vector)),
            "max": float(np.max(feature_vector))
        }
    }
@app.route('/predict', methods=['POST'])
def predict():
    data = request.get_json(silent=True) or {}
    if 'ecg_signal' not in data:
        return jsonify({"error": "'ecg_signal' is required"}), 400
    ecg_signal = np.array(data['ecg_signal'], dtype=float)
    if ecg_signal.size == 0:
        return jsonify({"error": "'ecg_signal' is empty"}), 400
    try:
        original_frequency = float(data.get('original_frequency', 0))
    except (TypeError, ValueError):
        original_frequency = 0
    if original_frequency <= 0:
        return jsonify({"error": "'original_frequency' must be a positive number"}), 400
    heart_rate = data.get('heart_rate', 75)
    preprocessed_signal = ecg_preprocessing(ecg_signal, original_frequency)
    input_tensor = torch.from_numpy(preprocessed_signal[0]).unsqueeze(0).float()
    with torch.no_grad():
        outputs = model(input_tensor)
        last_hidden_state = outputs.last_hidden_state
        feature_vector = torch.mean(last_hidden_state, dim=1).numpy()
    analysis_result = interpret_feature_vector(feature_vector, heart_rate)
    return jsonify(analysis_result)
if __name__ == '__main__':
    print("Starting Python backend for HuBERT-ECG...")
    app.run(port=5001, debug=True)
